import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link';
import CharacterService from '../services/CharacterService';
import styles from '../styles/Home.module.css'

const Home: NextPage = ({ data }: any) => {
  console.log(data)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to the Rick and Morty App!
        </h1>

        <div className={styles.grid}>
          {data.results.map(({ id, image, name, species }: any) => (
            <Link href={`character/${id}`} key={`${id}-${name}`}>
              <div className={styles.character}>
                <div>
                  <img src={image} alt="name" />
                </div>
                <div>
                  <h5 className={styles.names}>{name}</h5>
                  <p className={styles.species}>{species}</p>
                </div>
              </div>
            </Link>))
          }
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export async function getServerSideProps() {
  const res = await CharacterService.getCharacters();
  return {
      props: {
        data: res.data
      }, // will be passed to the page component as props
  }
}

export default Home
